# Gets a page of characters from a given show.
query ($showId: Int, $page: Int) {
  Media(id: $showId) {
    characters(page: $page) {
      pageInfo {
        hasNextPage
        total
        perPage
      }
      edges {
        node {
          id
          name {
            first
            last
            native
            alternative
          }
          image {
            medium
          }
        }
        voiceActors(language: JAPANESE) {
          id
          name {
            first
            last
          }
          image {
            medium
          }
        }
      }
    }
  }
}
